name: 2021-03-skeleton-dev-push
on:
  push:
    paths:
      - 2021-03-skeleton/**
    branches:
      - main
      - develop
      - feature/*
      - fix/*
      - refactor/*

defaults:
  run:
    working-directory: 2021-03-skeleton

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Go Setup
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - name: Go Cache
        uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

  lint:
    name: Use Lint Action
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.36
          working-directory: 2021-03-skeleton
          args: -c ./configs/.golangci.yml

  test:
    name: Make Go Test
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: make go-test

  notify:
    name: Slack Notification
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_GITHUB }}
        with:
          author_name: ${{ github.repository }}
          status: ${{ job.status }}
          fields: ref,commit,author,message,repo,workflow
        if: always()
